# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ec2-3-111-53-139.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: cd python-app && git pull && python test_sum_unittest.py
